trailingComma:
  - true
  - multiline:
    objects: always
    arrays: always
    functions: never
    typeLiterals: ignore
  - esSpecCompliant: true
tabWidth: 2
semi: true
singleQuote: true
printWidth: 120
jsxSingleQuote: true
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always
